const actionTypes = {
  LOAD_ITEMS_LIST: 'LOAD_ITEMS_LIST',
  LOAD_ITEM: 'LOAD_ITEM',
  LOAD_SHOPPING_CART: 'LOAD_SHOPPING_CART',
  PUT_ITEM_IN_CART: 'PUT_ITEM_IN_CART',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
  FILTER_ITEMS: 'FILTER_ITEMS',
};

export default actionTypes;
