const actionTypes = {
  LOAD_PRODUCT: 'LOAD_PRODUCT',
  LOAD_PRODUCT_DETAIL: 'LOAD_PRODUCT_DETAIL',
  LOAD_BASKET: 'LOAD_BASKET',
  LOAD_PRODUCT_BASKET: 'LOAD_PRODUCT_BASKET',
  LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR',
};

export default actionTypes;
