const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_PRODUCT_DETAIL: 'LOAD_PRODUCT_DETAIL',
  LOAD_PRODUCT_DETAIL_ERROR: 'LOAD_PRODUCT_DETAIL_ERROR',
  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',
  LOAD_SHOPPING_CART: 'LOAD_SHOPPING_CART',
  LOAD_SHOPPING_CART_ERROR: 'LOAD_SHOPPING_CART_ERROR',
  PUT_ITEM_IN_CART: 'PUT_ITEM_IN_CART',
  PUT_ITEM_IN_CART_ERROR: 'PUT_ITEM_IN_CART_ERROR',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
  DELETE_ITEM_FROM_CART_ERROR: 'DELETE_ITEM_FROM_CART_ERROR',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  LOGIN_USER_GOOGLE_ERROR: 'LOGIN_USER_GOOGLE_ERROR',
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
  RESET_FILTERS: 'RESET_FILTERS',
  SEND_ORDER: 'SEND_ORDER',
  SEND_ORDER_ERROR: 'SEND_ORDER_ERROR',

};

export default actionTypes;
