const actionTypes = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  LOAD_PROJECTS_ERROR: 'LOAD_PROJECTS_ERROR',
  LOAD_PROJECT: 'LOAD_PROJECT',
  LOAD_PROJECT_ERROR: 'LOAD_PROJECT_ERROR',
  LOAD_LOGIN: 'LOAD_LOGIN',
  LOAD_LOGIN_ERROR: 'LOAD_LOGIN_ERROR',
};

export default actionTypes;
