const actionTypes = {
  GET_INPUTS: 'GET_INPUTS',
  DELETE_INPUT: 'DELETE_INPUT',
  GET_INPUTS_ERROR: 'GET_INPUTS_ERROR',
  DELETE_INPUT_ERROR: 'DELETE_INPUT_ERROR',
  ADD_INPUT: 'ADD_INPUT',
  ADD_INPUT_ERROR: 'ADD_INPUT_ERROR',
};

export default actionTypes;
