const actionTypes = {
	LOAD_COINS_LIST: 'LOAD_COINS_LIST',
	ADD_TO_FAVORITE_LIST: 'ADD_TO_FAVORITE_LIST',
	REMOVE_FROM_FAVORITE_LIST: 'REMOVE_FROM_FAVORITE_LIST',
	ERROR_LOADING_DATA: 'ERROR_LOADING_DATA'
};

export default actionTypes;
