import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  user: {
    width: '100%',
    alignItems: 'center',
    marginTop: '5%',
    marginBottom: '10%',
  },
  no__user__title: {
    width: '100%',
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: '600',
  },
  user__title: {
    width: '100%',
    alignItems: 'center',
    marginBottom: '5%',
  },
  title__bar: {
    width: '75%',
    height: 4,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.60,
    shadowRadius: 4.65,
  },
  user__name: {
    width: '100%',
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: 'bold',
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 6,
    },
    shadowOpacity: 0.50,
    shadowRadius: 4.65,
  },
  user__userName: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '80%',
    marginTop: '5%',
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,

    elevation: 8,
  },
  user__userName__block__title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '50%',
  },
  user__userName__block: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
  },
  user__userName__text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#224864',
  },
  user__userName__name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2080DC',
  },
  user__profilePic: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  user__profilePic__image: {
    width: 200,
    height: 200,
    borderRadius: 100,
  },
  user__games: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '80%',
    marginTop: '5%',
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,

    elevation: 8,
  },
  user__games__title__block: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 10,
  },
  user__games__block: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
  },
  user__game__block: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    paddingTop: 5,
    paddingBottom: 5,
  },
  user__game__block__title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2089DC',
    textTransform: 'capitalize',
  },
  user__characters: {
    width: '100%',
    alignItems: 'center',
    marginTop: '10%',
    marginBottom: '5%',
  },
  user__characters__list: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
  },
  user__characters__list__block: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '80%',
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,

    elevation: 8,
  },
  user__characters__list__block__row: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: 5,
  },
  characterList__character__firstRow__name__block: {
    paddingRight: 10,
    borderWidth: 1,
    borderBottomColor: '#e5e5e5',
    borderTopColor: 'rgba(255,255,255,0)',
    borderRightColor: 'rgba(255,255,255,0)',
    borderLeftColor: 'rgba(255,255,255,0)',
  },
  characterList__character__firstRow__name__text: {
    fontSize: 23,
    fontWeight: 'bold',
    color: '#224864',
  },
  characterList__character__firstRow__text: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#224864',
  },
  characters__secondRow__text: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#224864',
  },
  button__delete: {
    width: 200,
    backgroundColor: '#D13C3C',
    borderRadius: 10,
  },
  modal__background: {
    shadowOpacity: 0.5,
  },
  editModal: {
    display: 'flex',
    justifyContent: 'space-around',
    width: '80%',
    maxHeight: 350,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  editModal__block: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  editModal__textBlock: {
    marginTop: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderWidth: 1,
    borderLeftColor: 'white',
    borderTopColor: 'white',
    borderRightColor: 'white',
    borderBottomColor: '#e5e5e5',
  },
  editModal__title: {
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#224864',
  },
  editModal__text: {
    color: '#2089dc',
    fontSize: 24,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  deleteModal__userName: {
    color: '#224864',
    fontSize: 22,
    fontWeight: 'bold',
  },
  deleteModal__warningText: {
    color: 'red',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonConfirmEditModal: {
    width: 200,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
  user__deleteButton__container: {
    marginTop: '10%',
  },

  addItemModal__title: {
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#224864',
  },
  addItemModal__title__input: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  editListModal__block: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  addItemModal__inputText: {
    paddingLeft: 5,
    paddingRight: 5,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2089dc',
    borderWidth: 1,
    borderBottomColor: '#e5e5e5',
    borderTopColor: 'rgba(255,255,255,0)',
    borderRightColor: 'rgba(255,255,255,0)',
    borderLeftColor: 'rgba(255,255,255,0)',
  },
  addItemModal__block__row: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
  },
  addItemModal__row__name: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingRight: 10,
  },
  addItemModal__row__garbage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  addIcon: {
    width: 40,
    height: 40,
    marginTop: 5,
    marginBottom: 5,
  },
  editItemModal__buttons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    marginTop: 15,
  },
  garbageIcon: {
    width: 40,
    height: 40,
  },
  deleteModal: {
    display: 'flex',
    justifyContent: 'space-around',
    width: '80%',
    maxHeight: 250,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
});

export default styles;
