const actionTypes = {
    LOAD_COMPONENTS: 'LOAD_COMPONENTS',
    LOAD_COMPONENTS_ERROR: 'LOAD_COMPONENTS_ERROR',
    LOAD_SINGLE_COMPONENT: 'LOAD_SINGLE_COMPONENT',
    LOAD_SINGLE_COMPONENT_ERROR: 'LOAD_SINGLE_COMPONENT_ERROR',
    LOAD_SHOPPING_CART: 'LOAD_SHOPPING_CART',
    LOAD_SHOPPING_CART_ERROR: 'LOAD_SHOPPING_CART_ERROR',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_CART_ERROR: 'ADD_TO_CART_ERROR'
}

module.exports = actionTypes;