const actionTypes = {
  LOAD_WORKOUTS: 'LOAD_WORKOUTS',
  LOAD_WORKOUTS_ERROR: 'LOAD_WORKOUTS_ERROR',
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_SIGNOUT: 'AUTH_SIGNOUT',
  AUTH_SIGNOUT_ERROR: 'AUTH_SIGNOUT_ERROR',
  ADD_USER: 'ADD_USER',
  ADD_USER_ERROR: 'ADD_USER_ERROR',
  SAVE_USER: 'SAVE_USER',
  SAVE_USER_ERROR: 'SAVE_USER_ERROR',
  CREATE_BOOKING: 'CREATE_BOOKING',
  CREATE_BOOKING_ERROR: 'CREATE_BOOKING_ERROR',
  FETCH_USER: 'FETCH_USER',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',
};

export default actionTypes;
