const typeActions = {
	LOAD_HEROES: 'LOAD_HEROES',
	ADD_HEROES: 'ADD_HEROES',
	REMOVE_HEROES: 'REMOVE_HEROES',
	UPDATE_HEROES: 'UPDATE_HEROES',
	LOAD_HERO: 'LOAD_HERO'
};

export default typeActions;
