const typeActions = {
	LOAD_HEROES: 'LOAD_HEROES',
	ADD_HEROES: 'ADD_HEROES',
	REMOVE_HEROES: 'REMOVE_HEROES',
	UPDATE_HEROES: 'UPDATE_HEROES',
	LOAD_HERO: 'LOAD_HERO',
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
	AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR'
};

export default typeActions;
