const actionTypes = {
    LOAD_PRODUCTS: 'LOAD_PRODUCTS',
    LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
    LOAD_PRODUCT:'LOAD_PRODUCT',
    LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR',
    CLEAN_PRODUCT_DETAIL: 'CLEAN_PRODUCT_DETAIL',
    LOAD_BASKET: 'LOAD_BASKET',
    DELETE_PRODUCT: 'DELETE_PRODUCT'
}

export default actionTypes;