import { Videogame } from './videogame';

export const VIDEOGAMES: Videogame[] = [
    {
        id: 1,
        name: 'Immortals Fenyx Rising',
        genre: ['Action', 'Adventure'],
        platforms: ['PlayStation 4', 'Xbox One', 'Nintendo Switch'],
        developer: 'Ubisoft',
        cover: 'https://static.xtralife.com/conversions/5RC8-0YD5270285-fullhd_w1920_h1080_q75-ps4immortalsfenyxrising-1600071221.png',
        images: ['https://static.xtralife.com/conversions/89CX-48MZ270290-fullhd_w1920_h1080_q75-ifr-glidingaphrodite-1600071446.png',
            'https://static.xtralife.com/conversions/WJCQ-Z3WD270291-fullhd_w1920_h1080_q75-ifr-axeshowcase-1600071447.png',
            'https://static.xtralife.com/conversions/D9C5-72XK270288-fullhd_w1920_h1080_q75-ifr-minotaurhammer-wings-1600071446.png',
            'https://static.xtralife.com/conversions/98CX-0962270289-fullhd_w1920_h1080_q75-ifr-harpyattack-1600071446.png'],
        description: ['Immortals Fenyx Rising™ brings grand mythological adventure to life. Play as Fenyx, a new winged demigod on a quest to save the Greek gods and their home from a dark curse. Take on mythological beasts, master the legendary powers of the gods and defeat Typhon, the deadliest Titan in Greek mythology, in an epic fight for the ages.',
            'The fate of the world is at stake – you are the gods’ last hope.',
            'Immortals Fenyx Rising is a fresh and witty take on the open world action adventure genre, featuring dynamic action, combat and stories inspired by Greek mythology. Roam freely across a beautifully stylized world and use extraordinary abilities gifted by the gods against fearsome mythological monsters. Treacherous trials, heroic feats and the very underworld itself await your bravery. Experience a tale for the ages, of gods and monsters, and become the legend you were destined to be.',
            'WIELD THE POWER OF GODS',
            'The gods of Olympus have blessed you with gifts: the wings of Daidalos, the sword of Achilles, the bow of Odysseus, and more, as well as legendary powers that will help turn the tides of battle. Use them to fight mythical monsters, solve ancient puzzles and explore the vast open world.',
            'CONFRONT MYTHOLOGICAL ENEMIES',
            'Face off against legendary beasts like Cyclops, Medusa, or Minotaur, and confront corrupted heroes such as Achilles. Take them on in fast-paced aerial and melee combat, combining your god-given abilities and weapons.',
            'EXPLORE A STYLIZED OPEN WORLD',
            'Discover a beautifully rendered and vibrant fantasy world. Traverse, climb or explore by air across seven unique regions, each inspired by the gods.',
            'OVERCOME HEROIC TRIALS',
            'Use your wit and special abilities to solve challenging puzzles and mind-bending vaults or partake in high-strategy boss battles to increase your power and upgrade your skills.',
            'BUILD YOUR LEGEND',
            "Customize your character's appearance and discover new armor and gear inspired by Greek mythology. Gather materials across the world to craft powerful items and upgrade your gear in your quest to fulfill your destiny."],
        pegi: '12+',
        price: 59.95,
        salePrice: 59.95,
        stock: true,
        release: '03-12-2020',
        comments: ['nananna', 'lolololo']
    },
    {
        id: 2,
        name: 'Sekiro: Shadows Die Twice',
        genre: ['Action', 'Adventure', 'Rol', 'RPG'],
        platforms: ['PlayStation 4'],
        developer: 'From Software',
        cover: 'https://static.xtralife.com/conversions/JQCP-5421258125-fullhd_w1920_h1080_q75-ps4sekirogoty-1587130551.png',
        images: ['https://static.xtralife.com/conversions/E89C-97Y871948-fullhd_w1920_h1080_q75-sekiro-21-1550747301.png',
            'https://static.xtralife.com/conversions/EWJC-RX7W71949-fullhd_w1920_h1080_q75-sekiro-24-1550747301.png',
            'https://static.xtralife.com/conversions/EWJC284V2000-fullhd_w1920_h1080_q75-03-1536322516.png',
            'https://static.xtralife.com/conversions/E60C-J26371950-fullhd_w1920_h1080_q75-sekiro-22-1550747301.png'],
        description: ['Carve your own clever path to vengeance in an all-new adventure from developer FromSoftware, creators of Bloodborne and the Dark Souls series.',
        'In Sekiro: Shadows Die Twice you are the “one-armed wolf”, a disgraced and disfigured warrior rescued from the brink of death. Bound to protect a young lord who is the descendant of an ancient bloodline, you become the target of many vicious enemies, including the dangerous Ashina clan. When the young lord is captured, nothing will stop you on a perilous quest to regain your honor, not even death itself.',
        'Explore late 1500s Sengoku Japan, a brutal period of constant life and death conflict, as you come face to face with larger than life foes in a dark and twisted world. Unleash an arsenal of deadly prosthetic tools and powerful ninja abilities while you blend stealth, vertical traversal, and visceral head to head combat in a bloody confrontation.', 
        'Take Revenge. Restore your honor. Kill Ingeniously.'],
        pegi: '18+',
        price: 59.95,
        salePrice: 39.95,
        stock: true,
        release: '22-03-2019',
        comments: ['nananna', 'lolololo']
    },
    {
        id: 3,
        name: 'Cyberpunk 2077',
        genre: ['Action', 'Rol', 'RPG'],
        platforms: ['PlayStation 4', 'Xbox One'],
        developer: 'CD Projekt RED',
        cover: 'https://static.xtralife.com/conversions/V2MC-2282234123-fullhd_w1920_h1080_q75-cyberpunk2077s4d1-1560117222.png',
        images: ['https://static.xtralife.com/conversions/1MCQ-20KM265054-fullhd_w1920_h1080_q75-1-cyberpunk2077-a-mercenary-on-the-rise-rgb-1593162636.png',
            'https://static.xtralife.com/conversions/RJC5-8ZXN265056-fullhd_w1920_h1080_q75-9-cyberpunk2077-lucky-number-13-rgb-1593162640.png',
            'https://static.xtralife.com/conversions/60CY-N86J265062-fullhd_w1920_h1080_q75-3-cyberpunk2077-always-bring-a-gun-to-a-knife-fight-rgb-1593162641.png',
            'https://static.xtralife.com/conversions/D9C5-Q8NQ265058-fullhd_w1920_h1080_q75-5-cyberpunk2077-outnumbered-but-not-outgunned-rgb-1593162641.png'],
        description: ['Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character’s cyberware, skillset and playstyle, and explore a vast city where the choices you make shape the story and the world around you.',
            'The game comes with the following physical items:',
            'Case with game discs',
            'World Compendium detailing the game’s setting and lore',
            'Postcards from Night City',
            'Map of Night City',
            'Stickers',
            'Digital goodies included:',
            'Game soundtrack',
            'Art booklet featuring a selection of art from the game',
            'Cyberpunk 2020 sourcebook',
            'Wallpapers for desktop and mobile'],
        pegi: '18+',
        price: 59.95,
        salePrice: 59.95,
        stock: true,
        release: '10-12-2020',
        comments: ['nananna', 'lolololo']
    }
];