import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  inventory: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: '5%',
    marginBottom: '5%',
  },
  inventory__title: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginBottom: '5%',
  },
  title__bar: {
    width: '75%',
    height: 4,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.60,
    shadowRadius: 4.65,
  },
  inventory__title__text: {
    width: '100%',
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: 'bold',
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 6,
    },
    shadowOpacity: 0.50,
    shadowRadius: 4.65,
  },
  inventory__category: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '80%',
    marginTop: '10%',
    padding: 20,
    paddingTop: 10,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,

    elevation: 8,
  },
  inventory__category__title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  category__title__name: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '70%',
  },
  category__title__addIcon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: '30%',
  },
  inventory__category__title__text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  inventory__category__item: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '95%',
    marginBottom: 15,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,
    elevation: 8,
  },
  inventory__category__item__title: {
    width: '100%',
    alignItems: 'flex-start',
    marginBottom: 5,
  },
  inventory__category__item__title__text: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  inventory__category__item__text: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#224864',
  },
  inventory__category__item__row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
    marginTop: 5,
    marginBottom: 5,
    paddingRight: 5,
  },
  inventory__category__item__row__name: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '50%',
    paddingRight: 20,
  },
  inventory__category__item__row__value: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    width: '50%',
  },
  addIcon__block: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
    marginBottom: 80,
    position: 'absolute',
    right: 0,
    bottom: 0,
    zIndex: 99,
  },
  addIcon: {
    width: 45,
    height: 45,
  },
  categoryModal: {
    display: 'flex',
    alignItems: 'center',
    width: '80%',
    height: 200,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  categoryModal__block: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  categoryModal__title: {
    marginTop: '5%',
    fontSize: 24,
    fontWeight: 'bold',
    color: '#224864',
  },
  categoryModal__text: {
    width: '100%',
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  categoryModal__button: {
    width: 200,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
  editCategoryModal: {
    display: 'flex',
    alignItems: 'center',
    width: '80%',
    height: 220,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  editCategoryModal__buttons: {
    display: 'flex',
    flexDirection: 'row-reverse',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
  },
  editCategoryModal__editButton: {
    width: 120,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
  editCategoryModal__deleteButton: {
    width: 120,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#D13C3C',
    borderRadius: 10,
  },
  deleteCategoryModal: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '80%',
    height: 250,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  deleteCategoryModal__block: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    padding: 10,
    paddingBottom: 0,
  },
  deleteCategoryModal__text: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#224864',
  },
  deleteCategoryModal__category__name: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2089dc',
  },
  deleteCategoryModal__warningText: {
    marginBottom: 10,
    textAlign: 'center',
    color: 'red',
    fontSize: 18,
    fontWeight: 'bold',
  },
  addItemModal: {
    display: 'flex',
    justifyContent: 'space-around',
    width: '80%',
    maxHeight: 350,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  addItemModal__scroll: {
    width: '100%',
    height: '100%',
  },
  addItemModal__block: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  addItemModal__title: {
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#224864',
  },
  addItemModal__title__input: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  addItemModal__block__title__row: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 15,
    marginBottom: 15,
    paddingLeft: 10,
  },
  addItemModal__block__row: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingLeft: 10,
  },
  addItemModal__row__name: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '43%',
    paddingRight: 10,
  },
  addItemModal__row__value: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '43%',
  },
  addItemModal__row__garbage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '14%',
  },
  addItemModal__itemName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#224864',
  },
  addItemModal__inputText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2089dc',
  },
  garbageIcon: {
    width: 40,
    height: 40,
  },
  addBlueIcon: {
    width: 45,
    height: 45,
    marginTop: 20,
  },
  addItemModal__button: {
    width: 200,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
  editItemModal__buttons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
  },
  editItemModal__editButton: {
    width: 120,
    marginTop: 20,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: '#D13C3C',
  },
  editItemModal__deleteButton: {
    width: 120,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
});

export default styles;
