const actionTypes = {
  LOAD_USER: 'LOAD_USER',
  LOAD_ERROR: 'LOAD_ERROR',
  LOAD_SERVICES: 'LOAD_SERVICES',
  LOAD_APPOINTMENT_SERVICE: 'LOAD_APPOINTMENT_SERVICE',
  LOAD_APPOINTMENT_BARBER: 'LOAD_APPOINTMENT_BARBER',
  LOAD_APPOINTMENT_DAY: 'LOAD_APPOINTMENT_DAY',
  LOAD_APPOINTMENT_WEEK_DAY: 'LOAD_APPOINTMENT_WEEK_DAY',
  LOAD_APPOINTMENT_HOUR: 'LOAD_APPOINTMENT_HOUR',
  LOAD_APPOINTMENT_MONTH: 'LOAD_APPOINTMENT_MONTH',
  LOAD_APPOINTMENT_YEAR: 'LOAD_APPOINTMENT_YEAR',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  LOGIN_USER_GOOGLE_ERROR: 'LOGIN_USER_GOOGLE_ERROR',
  LOGIN_USER_MONGO: 'LOGIN_USER_MONGO',
  LOAD_BARBER: 'LOAD_BARBER',
  LOAD_BARBER_NAME: 'LOAD_BARBER_NAME',
  LOAD_SERVICE_NAME: 'LOAD_SERVICE_NAME',
  RESERVATION_SUCCES: 'RESERVATION_SUCCES',
  LOAD_RESERVATIONS: 'LOAD_RESERVATIONS',
  LOAD_RESERVATION_USER_ID: 'LOAD_RESERVATION_USER_ID'
}
export default actionTypes
