const actionTypes = {
	LOAD_PRODUCTS: 'LOAD_PRODUCTS',
	LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
	LOAD_PRODUCT_DETAIL: "LOAD_PRODUCT_DETAIL",
	LOAD_PRODUCT_DETAIL_ERROR: "LOAD_PRODUCT_DETAIL_ERROR"
};

export default actionTypes;
