const actionAuthTypes = {
  CHECK_LOGIN_SUCCESS: 'CHECK_LOGIN_SUCCESS',
  CHECK_LOGIN_ERROR: 'CHECK_LOGIN_ERROR',
  IS_LOGGING: 'IS_LOGGING',
  IS_NOT_LOGGING: 'IS_NOT_LOGGING',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR'
}
export default actionAuthTypes
