const actionLocationTypes = {
  PERMISSIONS_NOT_ACCEPTED: 'PERMISSIONS_NOT_ACCEPTED',
  PERMISSIONS_ERROR: 'PERMISSIONS_ERROR',
  LOCATION_SUCCESS: 'LOCATION_SUCCESS',
  LOCATION_ERROR: 'LOCATION_ERROR',
  CITY_SUCCESS: 'CITY_SUCCESS',
  CITY_ERROR: 'CITY_ERROR'
}
export default actionLocationTypes
