const actionTypes = {
  LOAD_PROMOTIONS: 'LOAD_PROMOTIONS',
  LOAD_PROMOTIONS_ERROR: 'LOAD_PROMOTIONS_ERROR',
  LOAD_PROMOTION: 'LOAD_PROMOTION',
  LOAD_PROMOTION_ERROR: 'LOAD_PROMOTION_ERROR',
  LOAD_ESTABLISHMENT: 'LOAD_ESTABLISHMENT',
  LOAD_ESTABLISHMENT_ERROR: 'LOAD_ESTABLISHMENT_ERROR',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  ADD_AND_LOAD_USER: 'ADD_AND_LOAD_USER',
  ADD_AND_LOAD_USER_ERROR: 'ADD_AND_LOAD_USER_ERROR',
  ADD_FAVORITE: 'ADD_FAVORITE',
  ADD_FAVORITE_ERROR: 'ADD_FAVORITE_ERROR',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
  DELETE_FAVORITE_ERROR: 'DELETE_FAVORITE_ERROR'
}
export default actionTypes
