const actionTypes = {
    LOAD_TUPPERS: 'LOAD_TUPPERS',
    LOAD_TUPPER: 'LOAD_TUPPER',
    LIST_ERROR: 'LIST_ERROR',
    DETAIL_ERROR: 'DETAIL_ERROR',
    ADD_RECIPE: 'ADD_RECIPE',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    AUTH_SIGNOUT: 'AUTH_SIGNOUT',
    AUTH_SIGNOUT_ERROR:'AUTH_SIGNOUT_ERROR',
    AUTH_SIGNUP: 'AUTH_SIGNUP',
    AUTH_SIGNUP_ERROR: 'AUTH_SIGNUP_ERROR'
}
  export default actionTypes;