const actionTypes = {
  LOAD_BEERS: 'LOAD_BEERS',
  LOAD_BEERS_ERROR: 'LOAD_BEERS_ERROR',
  LOAD_BEER_DETAIL: 'LOAD_BEER_DETAIL',
  LOAD_BEER_DETAIL_ERROR: 'LOAD_BEER_DETAIL_ERROR',
  LOAD_BEERS_BY_MALT: 'LOAD_BEERS_BY_MALT',
  LOAD_BEERS_BY_MALT_ERROR: 'LOAD_BEERS_BY_MALT_ERROR',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_USER_GOOGLE: 'LOGOUT_USER_GOOGLE',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  FILTER_BEERS: 'FILTER_BEERS',
  LOAD_BEERS_BY_HOP: 'LOAD_BEERS_BY_HOP',
  LOAD_BEERS_BY_HOP_ERROR: 'LOAD_BEERS_BY_HOP_ERROR'

};

export default actionTypes;
