const actionTypes = {
  LOAD_CHARACTERS: 'LOAD_CHARACTERS',
  LOAD_CHARACTER: 'LOAD_CHARACTER',
  LOAD_CHARACTER_ID: 'LOAD_CHARACTER_ID',
  UPDATE_CHARACTER: 'UPDATE_CHARACTER',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ID: 'LOAD_USER_ID',
  LOAD_ERROR: 'LOAD_ERROR',
};

export default actionTypes;
