const actionTypes = {
	LOAD_HEROES: 'LOAD_HEROES',
	DELETE_HEROES: 'DELETE_HEROES',
	ADD_HERO: 'ADD_HERO',
	UPDATE_HERO: 'UPDATE_HERO',
	AUTH_SIGNOUT_ERROR: 'AUTH_LOGIN',
	AUTH_LOGIN: 'AUTH_LOGIN_ERROR',
	AUTH_LOGIN_ERROR: 'AUTH_SIGNOUT',
	AUTH_SIGNOUT: 'AUTH_SIGNOUT_ERROR'
};

export default actionTypes;
