const actionTypes = {
	LOAD_OPTIONFLIGHTS: 'LOAD_OPTIONFLIGHTS',
	LOAD_PASSENGERS: 'LOAD_PASSENGERS',
	LOAD_CLASSTYPE: 'LOAD_CLASSTYPE',
	LOAD_MADRIDBARCELONA: 'LOAD_MADRIDBARCELONA',
	ERASE_FORM: 'ERASE_FORM'
};

export default actionTypes;
