const actionTypes = {
  LOAD_TODOLIST: 'LOAD_TODOLIST',
  POST_TODOLIST_ITEM: 'POST_TODOLIST_ITEM',
  POST_TODOLIST_ITEM_ERROR: 'POST_TODOLIST_ITEM_ERROR',
  DELETE_TODOLIST_ITEM: 'DELETE_TODOLIST_ITEM',
};

export default actionTypes;
