const actionTypes = {
    LOAD_LIST: 'LOAD_LIST',
    LOAD_LIST_ERROR: 'LOAD_LIST_ERROR',
    CREATE_PROJECT:'CREATE_PROJECT',
    CREATE_PROJECT_ERROR:'CREATE_PROJECT_ERROR',
    DELETE_PROJECT_ERROR:'DELETE_PROJECT_ERROR',
    DELETE_PROJECT:'DELETE_PROJECT'
}

export default actionTypes;