const actionTypes = {
	REQUEST_TOKEN: 'REQUEST_TOKEN',
	TOKEN_ERROR: 'TOKEN_ERROR',
	REQUEST_ARTIST: 'REQUEST_ARTIST',
	ARTIST_ERROR: 'ARTIST_ERROR',
	REQUEST_ARTISTS: 'REQUEST_ARTISTS',
	ARTISTS_ERROR: 'ARTISTS_ERROR'
};

export default actionTypes;
