const actionTypes = {
	REQUEST_TOKEN: 'REQUEST_TOKEN',
	TOKEN_ERROR: 'TOKEN_ERROR',
	REQUEST_ARTIST: 'REQUEST_ARTIST',
	ARTIST_ERROR: 'ARTIST_ERROR',
	REQUEST_OTHER_ARTISTS: 'REQUEST_OTHER_ARTISTS',
	REQUEST_TOP_ARTIST_TRACKS: 'REQUEST_TOP_ARTIST_TRACKS',
	REQUEST_OTHER_ARTISTS_TOP_ARTIST_TRACKS:
		'REQUEST_OTHER_ARTISTS_TOP_ARTIST_TRACKS',
	ARTISTS_ERROR: 'ARTISTS_ERROR',
	REQUEST_IMAGE: 'REQUEST_IMAGE',
	RESET_GAME: 'RESET_GAME',
	SUM_SCORE: 'SUM_SCORE',
	SUM_FAILS: 'SUM_FAILS'
};

export default actionTypes;
