const actionsTypes = {
  LOAD_PRODUCT_LIST: 'LOAD_PRODUCT_LIST',
  LOAD_PRODUCT_BY_MODEL: 'LOAD_PRODUCT_BY_MODEL',
  ADD_PRODUCT_CART: 'ADD_PRODUCT_CART',
  DELETE_PRODUCT_CART: 'DELETE_PRODUCT_CART',
  LOAD_LAPTOP_ERROR: 'LOAD_LAPTOP_ERROR',
  LOAD_CART_LIST: 'LOAD_CART_LIST',
};

export default actionsTypes;
