const actionTypes = {
  LOAD_LIST: 'LOAD_LIST',
  LOAD_LIST_ERROR: 'LOAD_LIST_ERROR',
  ADD_TO_CARRITO: 'ADD_TO_CARRITO',
  SHOW_FAVLIST: 'SHOW_FAVLIST',
  DELETE_FROM_CARRITO: 'DELETE_FROM_CARRITO',
};

export default actionTypes;
