import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  headerWrapper: {
    position: 'relative',
    top: 0,
    zIndex: 1,
    width: '100%',
    backgroundColor: 'rgb(230, 84, 84)',
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  upperHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: 'black',
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingBottom: 15,
  },
  profilePicture: {
    height: 60,
    width: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  tabNavigator: {
    borderBottomColor: 'white',
    color: 'white',
    fontSize: 18,
  },
  recipePhoto: {
    height: 100,
    width: 155,
    borderRadius: 5,
    marginRight: 15,
  },
  recipeNameContainer: {
    flexGrow: 1,
    paddingRight: 15,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  recipeName: {
    fontSize: 20,
    flex: 1,
    flexWrap: 'wrap',
    textAlign: 'center',
    marginTop: 5,
  },
  arrowImage: {
    width: 95,
    height: 105,
    position: 'absolute',
    right: 5,
    top: -122,
    transform: [{ rotate: '-15deg' }],
  },
  plusSignWrapper: {
    alignItems: 'flex-end',
    padding: 20,
    position: 'absolute',
    top: 380,
    right: 15,
    height: 80,
  },
  plusSignContainer: {
    position: 'absolute',
    top: 155,
    right: -50,
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgb(150, 89, 42)',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  plusSignContainerAdded: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgb(150, 89, 42)',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  plusSign: {
    fontSize: 70,
    fontFamily: 'serif',
    color: 'white',
    textShadowColor: 'black',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  favoriteCardContainer: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  favoriteCard: {
    borderRadius: 5,
    backgroundColor: 'rgb(242, 242, 242)',
    elevation: 5,
    marginHorizontal: 10,
    marginTop: 4,
    marginBottom: 16,
  },
});

export default styles;
