const actionTypes = {
	LOAD_HEROES: 'LOAD_HEROES',
	LOAD_HEROES_ERROR: 'LOAD_HEROES_ERROR',
	LOAD_HERO_DETAIL: "LOAD_HERO_DETAIL",
	LOAD_HERO_DETAIL_ERROR: "LOAD_HERO_DETAIL_ERROR",
	CLEAN_UP : "CLEAN_UP"
};

export default actionTypes;
