const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_ERROR: 'GET_PRODUCT_ERROR',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_ERROR: 'ADD_PRODUCT_ERROR',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',
  GET_CART: 'GET_CART',
  GET_CART_ERROR: 'GET_CART_ERROR',
};

export default actionTypes;
