const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCT_DETAIL: 'LOAD_PRODUCT_DETAIL',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_SHOPPING_LIST: 'LOAD_SHOPPING_LIST',
};

export default actionTypes;
