import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  character: {
    width: '100%',
    alignItems: 'center',
    marginTop: '5%',
    marginBottom: '10%',
  },
  no__character__title: {
    width: '100%',
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: '600',
  },
  character__title: {
    width: '100%',
    alignItems: 'center',
    marginBottom: '5%',
  },
  title__bar: {
    width: '75%',
    height: 4,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.60,
    shadowRadius: 4.65,
  },
  character__name: {
    width: '100%',
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: 'bold',
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 6,
    },
    shadowOpacity: 0.50,
    shadowRadius: 4.65,
  },
  character__owner: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '80%',
    marginTop: '5%',
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,

    elevation: 8,
  },
  character__owner__text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#224864',
  },
  character__owner__info: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginRight: 5,
  },
  character__owner__profilePic: {
    width: 55,
    height: 55,
    marginLeft: 20,
    borderRadius: 50,
  },
  character__description: {
    display: 'flex',
    width: '80%',
    marginTop: '5%',
    padding: 10,
    paddingBottom: 12,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,
    elevation: 8,
  },
  character__description__row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: 10,
  },
  character__description__text: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#224864',
  },
  character__description__pressable: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    width: '60%',
  },
  character__description__button: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    width: '100%',
    borderWidth: 1,
    borderLeftColor: 'white',
    borderTopColor: 'white',
    borderRightColor: 'white',
    borderBottomColor: '#bcbcbc',
  },
  character__description__textButton: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2089dc',
  },
  character__set: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: '5%',
  },
  set__bar: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '60%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,

    elevation: 8,
  },
  character__set__text: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#224864',
  },
  character__set__icon: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  character__set__visible__icon: {
    width: 40,
    height: 40,
    marginRight: 10,
    marginLeft: 30,
  },
  character__button__container: {
    marginTop: '10%',
  },
  button__delete: {
    width: 200,
    backgroundColor: '#D13C3C',
    borderRadius: 10,
  },
  visibilityModal: {
    display: 'flex',
    alignItems: 'center',
    width: '50%',
    height: '15%',
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  modal__background: {
    shadowOpacity: 0.5,
  },
  editModal: {
    display: 'flex',
    alignItems: 'center',
    width: '80%',
    height: 200,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  editModal__block: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  editModal__textBlock: {
    paddingLeft: 20,
    paddingRight: 20,
    borderWidth: 1,
    borderLeftColor: 'white',
    borderTopColor: 'white',
    borderRightColor: 'white',
    borderBottomColor: '#e5e5e5',
  },
  editModal__text: {
    color: '#2089dc',
    fontSize: 18,
    fontWeight: 'bold',
  },
  deleteModal__warningText: {
    color: 'red',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonConfirmEditModal: {
    width: 200,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
});

export default styles;
