import { StyleSheet, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  sectionTitle: {
    marginTop: StatusBar.currentHeight,
    height: 70,
    fontSize: 30,
    color: 'black',
    textShadowColor: 'white',
    textShadowOffset: { width: 2, height: 2 },
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 20,
    borderBottomWidth: 1.5,
    width: '90%',
    paddingBottom: 15,
    lineHeight: 65,
    alignSelf: 'center',
  },
  menuSectionTitle: {
    textAlign: 'center',
    fontSize: 20,
    backgroundColor: 'rgb(230, 84, 84)',
    color: 'white',
    height: 40,
    lineHeight: 40,
  },
  favoriteCardContainer: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  favoriteCard: {
    borderRadius: 5,
    backgroundColor: 'rgb(242, 242, 242)',
    elevation: 5,
    marginHorizontal: 10,
    marginTop: 4,
    marginBottom: 16,
    flexDirection: 'row',
    position: 'relative',
  },
  selectedRecipeFilter: {
    zIndex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeIconContainer: {
    position: 'absolute',
    top: 5,
    left: 5,
    backgroundColor: 'rgb(225, 225, 225)',
    height: 25,
    width: 25,
    borderRadius: 25,
    borderColor: 'black',
    borderWidth: 0.5,
    zIndex: 3,
  },
  recipePhoto: {
    height: 100,
    width: 155,
    borderRadius: 5,
    marginRight: 15,
  },
  recipeNameContainer: {
    flexGrow: 1,
    paddingRight: 15,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  recipeName: {
    fontSize: 20,
    flex: 1,
    flexWrap: 'wrap',
    textAlign: 'center',
    marginTop: 5,
  },
  addRecipeToMenu: {
    fontSize: 35,
    fontFamily: 'serif',
    backgroundColor: 'white',
    height: 25,
    width: 25,
    lineHeight: 33,
    borderRadius: 25,
    textAlign: 'center',
    borderColor: 'black',
    borderWidth: 0.5,
    zIndex: 1,
  },
  createMenuButton: {
    position: 'absolute',
    bottom: 0,
    height: 60,
    backgroundColor: 'black',
    color: 'white',
    textAlign: 'center',
    lineHeight: 60,
    fontSize: 20,
  },
  addRecipeToMenuSection: {
    backgroundColor: 'rgba(250, 250, 250, 0.9)',
    position: 'relative',
    top: -9,
    right: 11.5,
    width: 110,
    borderRadius: 8,
    alignItems: 'center',
    borderColor: 'black',
    borderWidth: 0.5,
  },
  addRecipeToBreakfastOrLunch: {
    fontSize: 17,
    paddingVertical: 6,
    textAlign: 'center',
    borderBottomColor: 'black',
    borderBottomWidth: 1,
    width: '80%',
  },
});

export default styles;
