const actionTypes = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  LOAD_PROJECTS_ERROR: 'LOAD_PROJECTS_ERROR',
  LOAD_PROJECT: 'LOAD_PROJECT',
  LOAD_PROJECT_ERROR: 'LOAD_PROJECT_ERROR',
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_ERROR: 'CREATE_PROJECT_ERROR',
  USER_LOGOUT: 'USER_LOGOUT',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  APPLY_FILTERS: 'APPLY_FILTERS',
  RESET_FILTERS: 'RESET_FILTERS',
};

export default actionTypes;
