const actionTypes = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  LOAD_PROJECTS_ERROR: 'LOAD_PROJECTS_ERROR',
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_PROJECT_ERROR: 'CREATE_PROJECT_ERROR',
  GITHUB_LOGIN: 'GITHUB_LOGIN',
  GITHUB_LOGIN_ERROR: 'GITHUB_LOGIN_ERROR',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
};

export default actionTypes;
