const actionTypes = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  LOAD_PROJECTS_ERROR: 'LOAD_PROJECTS_ERROR',
  GITHUB_LOGIN: 'GITHUB_LOGIN',
  GITHUB_LOGIN_ERROR: 'GITHUB_LOGIN_ERROR',
};

export default actionTypes;
