const actionTypes = {
  LOAD_LIST: 'LOAD_LIST',
  LOAD_LIST_ERROR: 'LOAD_LIST_ERROR',
  DELETE_ITEM: 'DELETE_ITEM',
  DELETE_ITEM_ERROR: 'DELETE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  UPDATE_ITEM_ERROR: 'UPDATE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  ADD_ITEM_ERROR: 'ADD_ITEM_ERROR',
};
export default actionTypes;
