const actionTypes = {
  CHALLENGE_LIST_REQUEST: 'CHALLENGE_LIST_REQUEST',
  CHALLENGE_LIST_SUCCESS: 'CHALLENGE_LIST_SUCCESS',
  CHALLENGE_LIST_FAIL: 'CHALLENGE_LIST_FAIL',
  CHALLENGE_DETAILS_REQUEST: 'CHALLENGE_DETAILS_REQUEST',
  CHALLENGE_DETAILS_SUCCESS: 'CHALLENGE_DETAILS_SUCCESS',
  CHALLENGE_DETAILS_FAIL: 'CHALLENGE_DETAILS_FAIL',
  USERS_REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  USERS_REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  USERS_REGISTER_FAIL: 'USERS_REGISTER_FAIL',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  CHALLENGE_CREATE_REQUEST: 'CHALLENGE_CREATE_REQUEST',
  CHALLENGE_CREATE_SUCCESS: 'CHALLENGE_CREATE_SUCCESS',
  CHALLENGE_CREATE_FAIL: 'CHALLENGE_CREATE_FAIL',
  CHALLENGE_CREATE_RESET: 'CHALLENGE_CREATE_RESET',
  CHALLENGE_DELETE_REQUEST: 'CHALLENGE_DELETE_REQUEST',
  CHALLENGE_DELETE_SUCCESS: 'CHALLENGE_DELETE_SUCCESS',
  CHALLENGE_DELETE_FAIL: 'CHALLENGE_DELETE_FAIL',
};

export default actionTypes;
