import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  notes: {
    width: '100%',
    alignItems: 'center',
    marginTop: '5%',
    marginBottom: '10%',
  },
  character__title: {
    width: '100%',
    alignItems: 'center',
    marginBottom: '5%',
  },
  title__bar: {
    width: '75%',
    height: 4,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.60,
    shadowRadius: 4.65,
  },
  character__name: {
    width: '100%',
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontWeight: 'bold',
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 6,
    },
    shadowOpacity: 0.50,
    shadowRadius: 4.65,
  },
  notes__note: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '80%',
    marginTop: '10%',
    padding: 20,
    paddingTop: 10,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,
    elevation: 8,
  },
  inventory__category__title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  inventory__category__title__text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  addBlueIcon: {
    width: 40,
    height: 40,
  },
  note__row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '95%',
    marginTop: 10,
    marginBottom: 10,
  },
  note__row__dot: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '5%',
    marginRight: 10,
  },
  dotIcon: {
    width: 18,
    height: 18,
  },
  note__row__entry: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '95%',
    padding: 10,
    borderWidth: 1,
    borderBottomColor: '#bcbcbc',
    borderTopColor: 'white',
    borderLeftColor: 'white',
    borderRightColor: 'white',
  },
  note__row__entry__text: {
    color: '#2089DC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  addIcon__block: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
    marginBottom: 80,
    position: 'absolute',
    right: 0,
    bottom: 0,
    zIndex: 99,
  },
  addIcon: {
    width: 45,
    height: 45,
  },
  noteModal: {
    display: 'flex',
    alignItems: 'center',
    width: '80%',
    height: 200,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  noteModal__block: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  noteModal__title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#224864',
  },
  noteModal__text: {
    width: '90%',
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2089DC',
  },
  noteModal__button: {
    width: 200,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
  editNoteModal__buttons: {
    display: 'flex',
    flexDirection: 'row-reverse',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
  },
  editNoteModal__editButton: {
    width: 120,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#3D7BA8',
    borderRadius: 10,
  },
  editNoteModal__deleteButton: {
    width: 120,
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: '#D13C3C',
    borderRadius: 10,
  },
  deleteNoteModal__block: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    padding: 10,
    paddingBottom: 0,
  },
  deleteNoteModal__text: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#224864',
  },
  deleteNoteModal__note__name: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2089dc',
  },
  deleteNoteModal__warningText: {
    marginBottom: 10,
    textAlign: 'center',
    color: 'red',
    fontSize: 18,
    fontWeight: 'bold',
  },
  entryModal: {
    display: 'flex',
    alignItems: 'center',
    width: '80%',
    height: 300,
    maxHeight: 600,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  entryModal__title: {
    marginTop: 10,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#224864',
  },
  entryModal__text: {
    display: 'flex',
    justifyContent: 'flex-end',
    width: '100%',
    padding: 10,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2089DC',
    borderWidth: 1,
    borderColor: '#bcbcbc',
    borderRadius: 10,
    marginTop: 30,
    marginBottom: 50,
  },
  characterSheet__no_images: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    marginTop: 100,
    padding: 10,
    paddingBottom: 40,
    paddingTop: 40,
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.30,
    shadowRadius: 4.65,
    elevation: 8,
  },
  characterSheet__no_images__text: {
    width: '100%',
    color: '#224864',
    fontSize: 40,
    textAlign: 'center',
    fontWeight: 'bold',
  },
});

export default styles;
