const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_PRODUCT_DETAIL: 'LOAD_PRODUCT_DETAIL',
  LOAD_PRODUCT_DETAIL_ERROR: 'LOAD_PRODUCT_DETAIL_ERROR',
  PRODUCT_DETAIL_CLEANUP: 'PRODUCT_DETAIL_CLEANUP',
  LOAD_PRODUCT_CART: 'LOAD_PRODUCT_CART',
  LOAD_PRODUCT_CART_ERROR: 'LOAD_PRODUCT_CART_ERROR',
  ADD_ITEM_CART: 'ADD_ITEM_CART',
  ADD_ITEM_CART_ERROR: 'ADD_ITEM_CART_ERROR',
};

export default actionTypes;
