const actionTypes = {
    LOAD_TODOLIST: 'LOAD_TODOLIST',
    LOAD_TODOLIST_ERROR: 'LOAD_TODOLIST_ERROR',
    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',
    CLEAN_PRODUCT_DETAIL: 'CLEAN_PRODUCT_DETAIL',
}

export default actionTypes;