const actionTypes = {
    LOAD_TODOLIST: 'LOAD_TODOLIST',
    LOAD_TODOLIST_ERROR: 'LOAD_TODOLIST_ERROR',
    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',
    PUT_ITEM: 'PUT_ITEM',
    PUT_ITEM_ERROR: 'PUT_ITEM_ERROR'
}

export default actionTypes;