const actionTypes = {
	ADD_HERO: 'ADD_HERO',
	DELETE_HERO: 'DELETE_HERO',
	CHARGE_HEROES: 'CHARGE_HEROES',
	CHARGE_HEROES_ERROR: 'CHARGE_HEROES_ERROR',
	INCREMENT_ID: 'INCREMENT_ID'
};
export default actionTypes;
